<?php

namespace Welding\WeldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WelderRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WelderRepository extends EntityRepository
{
}
